language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
      sudo: required

install:
  - sh install-${TRAVIS_OS_NAME}.sh

script:
  - curl -sSL https://raw.githubusercontent.com/xp-runners/reference/master/setup.sh.in | sed -e "s/@VERSION@/7.0.0/g" > setup.sh
  - sh setup.sh
  - echo 'It worked!' > class-main.php
  - ./xp
